version: 2.1

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

executors:
  fermium-alpine:
    docker:
      - image: node:fermium-alpine
    environment:
      ## this enables colors in the output
      TERM: xterm
  cypress-chrome:
    docker:
      - image: cypress/browsers:node14.17.0-chrome88-ff89
    environment:
      ## this enables colors in the output
      TERM: xterm


orbs:
  node: circleci/node@5.0.1
  cypress: cypress-io/cypress@1.29.0

jobs:
  test:
    executor: fermium-alpine
    steps:
      - checkout
      - run: echo "<<pipeline.parameters.GHA_Event>>"
      - run: echo "<<pipeline.parameters.GHA_Action>>"
      - run: echo "<<pipeline.parameters.GHA_Actor>>"
      - run: echo "<<pipeline.parameters.GHA_Meta>>"
      - node/install-packages
      - run:
          name: run unit test
          command: npm run test
          environment:
            CI: "true"
            

workflows:
  test:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - test