version: 2.1

parameters:
  run-workflows:
    type: string
    default: ""

executors:
  fermium-alpine:
    docker:
      - image: node:fermium-alpine
    environment:
      ## this enables colors in the output
      TERM: xterm
  cypress-chrome:
    docker:
      - image: cypress/browsers:node14.17.0-chrome88-ff89
    environment:
      ## this enables colors in the output
      TERM: xterm


orbs:
  node: circleci/node@5.0.1
  cypress: cypress-io/cypress@1.29.0

jobs:
  test:
    executor: fermium-alpine
    steps:
      - checkout
      - node/install-packages
      - run:
          name: run unit test
          command: npm run test
          environment:
            CI: "true"
            
workflows:
  test:
    when:
      equal: ["test", << pipeline.parameters.run-workflows >>]
    jobs:
      - test