name: 'Check PR labeled'

on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - labeled

jobs:
  ready-to-test-labeled:
    name: 'check ready_to_test label'
    runs-on: ubuntu-latest
    env:
      TEST_WORKFLOWS_PATH: '.github/workflows/run-test.yml'
    if: github.event.label.name == 'ready to test'
    steps:
      - name: checkout github
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - run: echo ${{ github.event.pull_request.base.ref }}
      - name: call run-test workflows
        uses: '${{ github.event.repository.fullname }}/$TEST_WORKFLOW_PATH@${{ github.event.pull_request.base.ref }}'
        with:
          call_from: labeled

  remove-label:
    runs-on: ubuntu-latest
    needs: ready-to-test-labeled
    if: always()
    steps:
      - name: remove ready-to-test label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'ready to test'
      
    
    
  