name: deploy

on:
  workflow_call:
    inputs:
      target:
        description: target branch to deploy
        type: string
        required: true
    output:
      deploy-status:
        description: deployment status
        value: ''

env:
  # kslplus, kslplusstaging
  PROJECT_ID: ${{ github.event.push.ref == 'refs/heads/main' && 'chatapptest-edd0d' || 'chatapptest-edd0d' }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: npm ci && npm run build
      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHATAPPTEST_EDD0D }}'
          channelId: live
          projectId: '${{ env.PROJECT_ID }}'
