name: 'merge flow'

on:
  workflow_call:
    inputs:
      target-branch:
        required: true
        type: string

jobs:
  remove-previous-labeled:
    name: 'remove previous labeled'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: remove ready-to-test label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            'ready to test'
            'test success'
            'test failure'

  test:
    name: 'run test'
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install dependencies
        run: npm install
      - name: run test [ci mode]
        id: ci-test
        run: npm run test
        env:
          CI: true

  label-test-result:
    name: 'label test result'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: add test's result label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'test ${{ needs.test.result }}'
