name: merge hotfix

on:
  workflow_call:

jobs:
  merge:
    name: merge
    needs: [check_approval, rebase, test]
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - id: merge
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: ${{ github.event.pull_request.base.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # terminated if test failed.
    - name: comment merge failure
      continue-on-error: true
      if: ${{ job.steps.merge.status == 'failure' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: Merge failed! Please try again.
        reactions: '-1'

  deploy:
    name: deploy
    needs: merge
    runs-on: ubuntu-latest
    steps:
    - name: checkout base code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.base.ref }}
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: build
      run: npm ci --production && npm run build
    - id: deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      env:
        PROJECT_ID: chatapptest-edd0d
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        projectId: ${{ env.PROJECT_ID }}
        channelId: live
    # terminated if test failed.
    - name: comment deploy failure
      continue-on-error: true
      if: ${{ job.steps.deploy.status == 'failure' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: Deploy failed! Please try again.
        reactions: '-1'

  remove_label:
    name: remove label
    runs-on: ubuntu-latest
    steps:
      - name: remove ready_to_merge label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: merge hotfix
      