name: 'on pull request commit'

on:
  pull_request_target:
    branches:
      - dev
      - main
    types:
      - edited

jobs:
  remove-label:
    name: 'remove label'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: remove label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            'ready to test'
            'test success'
            'test failure'
            'ready to merge'
            'merge success'
            'merge failure'
