name: Preview to Firebasse Hosting on PR

on:
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

env:
  PROJECT_ID: chatapptest-edd0d

jobs:
  remove-label:
    name: 'remove label'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: remove label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            'ready to test'
            'test success'
            'test failure'
            'ready to merge'
            'merge success'
            'merge failure'

  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: npm ci && npm run build
      # more information at: https://github.com/marketplace/actions/deploy-to-firebase-hosting#options
      - name: preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHATAPPTEST_EDD0D }}'
          projectId: '${{ env.PROJECT_ID }}'
          expires: 7d