# name: test

# on:
#   workflow_call:

# jobs:
#   remove-previous-labeled:
#     name: remove previous labeled
#     runs-on: ubuntu-latest
#     continue-on-error: true
#     steps:
#       - name: remove label
#         uses: actions-ecosystem/action-remove-labels@v1
#         with:
#           labels: |
#             ready to test
#             test success
#             test failure

#   test:
#     name: run test
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout
#         uses: actions/checkout@v3
#       - name: setup node
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14
#       - name: install dependencies
#         run: npm install
#       - name: run test [ci mode]
#         id: ci-test
#         run: npm run test
#         env:
#           CI: true

#   log-result:
#     name: log test result
#     runs-on: ubuntu-latest
#     needs: test
#     if: always()
#     steps:
#       - name: add test result label
#         uses: actions-ecosystem/action-add-labels@v1
#         with:
#           labels: test ${{ needs.test.result }}
#       - name: comment test result
#         uses: peter-evans/create-or-update-comment@v2
#         env:
#           BRANCH: ${{ github.event.pull_request.head.ref }}
#           SHA: ${{ github.event.pull_request.head.sha }}
#           STATUS: ${{ needs.test.result == 'success' && ':white_check_mark::eggplant::sweat_drops:**passed**' || ':boom::shit::clown_face:**failed**' }}
#           REACTIONS: ${{ needs.test.result == 'success' && '+1, hooray' || '-1, eyes' }}
#         with:
#           issue-number: ${{ github.event.pull_request.number }}
#           body: |
#             **[${{env.SHA}}]** test report
#             | branch  | sha  | actions   | status  |
#             |---------|------|-----------|---------|
#             | ${{ env.BRANCH }} | ${{ env.SHA }} | unit test | ${{ env.STATUS }} |
#           reactions: '${{ env.REACTIONS }}'
